name: Update Ace Box Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - 810-feature-static-site-generator-for-project-documentation

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: yarn
          # cache-dependency-path: ace-box/docs/yarn.lock

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ace-box/docs/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('ace-box/docs/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          for i in {1..5}; do
            yarn install --frozen-lockfile && break || sleep 15
          done
        working-directory: docs

      - name: Build website
        run: yarn build
        working-directory: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com