
name: Deploy External Demo All

env:
  DEFAULT_EXTERNAL_USE_CASES: '[\"dynatrace-ace/basic-dt-demo.git\",\"dynatrace-ace/ace-box-ext-hot-aiops-2025.git@demo\"]'
  DEFAULT_PROVIDERS: '[\"gcloud\"]'
  DESTROY_RESOURCES: true
  USE_CASE_VALIDATION_TESTS_ENABLED: true
  DEFAULT_CUSTOM_DOMAIN: ""
  DEFAULT_ACE_BOX_NAME_PREFIX: "ace-box-gh-ext-demo"
  DT_TENANT: ${{ vars.DT_TENANT }}
  DT_URL_GEN3: ${{ vars.DT_URL_GEN3 }}
  DT_API_TOKEN: ${{ secrets.DT_API_TOKEN }}

on:
  # push:
  #   branches:
  #     - dev # Trigger after PR is merged to the dev branch
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
     
      providers:
        description: 'Select the providers to run (comma-separated). Example: ["gcloud","aws"]. For GCP, provide the GCP_CREDENTIALS_JSON in the Github repository secrets.'
        required: true
        default: '["gcloud"]'
        type: string

      destroy_resources:
        description: 'Select to enable resource destruction'
        required: true
        default: true
        type: boolean

      use_case_validation_tests_enabled:
        description: 'Select to enable use case validation tests'
        required: false
        default: false
        type: boolean

      custom_domain:
        description: "Custom Domain Name. Example: demo.ace-innovation.info. Keep empty for temporary validations."
        required: false
        default: ""
        type: string
      ace_box_name_prefix:
        description: "Ace-Box Name Prefix to identify the resources created by this workflow. Example: demo-ace-box."
        required: false
        default: "ace-box-gh-pr-validate"
        type: string

      # optional params for manual run
      dt_tenant:
        description: "Dynatrace Tenant. Keep empty to use the default tenant configured in the Github variables. For API Token, modify the DT_API_TOKEN secret in the Github repository settings."
        required: false
        default: ""
        type: string
      dt_url_gen3:
        description: "Dynatrace Environment URL Gen3. Keep empty to use the default tenant configured in the Github variables. For OAuth, modify the DT_OAUTH_CLIENT_ID and DT_OAUTH_CLIENT_SECRET secrets in the Github repository settings."
        required: false
        default: ""
        type: string

jobs:

  set_env_vars:
    runs-on: spot
    outputs:
      use_cases: ${{ steps.set_outputs.outputs.use_cases }}
      providers: ${{ steps.set_outputs.outputs.providers }}
      destroy_resources: ${{ steps.set_outputs.outputs.destroy_resources }}
      use_case_validation_tests_enabled: ${{ steps.set_outputs.outputs.use_case_validation_tests_enabled }}
      custom_domain: ${{ steps.set_outputs.outputs.custom_domain }}
      ace_box_name_prefix: ${{ steps.set_outputs.outputs.ace_box_name_prefix }}
      dt_tenant: ${{ steps.set_outputs.outputs.dt_tenant }}
      dt_url_gen3: ${{ steps.set_outputs.outputs.dt_url_gen3 }}
    steps:
      - name: Set Environment Variables
        id: set_env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "use_cases=${{ env.DEFAULT_EXTERNAL_USE_CASES }}" >> "$GITHUB_ENV"
            echo "providers=$(echo '${{ github.event.inputs.providers }}' )" >> "$GITHUB_ENV"
            echo "destroy_resources=$(echo '${{ github.event.inputs.destroy_resources }}' )" >> "$GITHUB_ENV"
            echo "use_case_validation_tests_enabled=$(echo ${{ github.event.inputs.use_case_validation_tests_enabled }} )" >> "$GITHUB_ENV"
            echo "custom_domain=$(echo '${{ github.event.inputs.custom_domain }}' )" >> "$GITHUB_ENV"
            echo "ace_box_name_prefix=$(echo '${{ github.event.inputs.ace_box_name_prefix }}' )" >> "$GITHUB_ENV"
            echo "dt_tenant=$(echo '${{ github.event.inputs.dt_tenant }}' )" >> "$GITHUB_ENV"
            echo "dt_url_gen3=$(echo '${{ github.event.inputs.dt_url_gen3 }}' )" >> "$GITHUB_ENV"
          else
            echo "use_cases=${{ env.DEFAULT_EXTERNAL_USE_CASES }}" >> "$GITHUB_ENV"
            echo "providers=${{ env.DEFAULT_PROVIDERS }}" >> "$GITHUB_ENV"
            echo "destroy_resources=${{ env.DESTROY_RESOURCES }}" >> "$GITHUB_ENV"
            echo "use_case_validation_tests_enabled=${{ env.USE_CASE_VALIDATION_TESTS_ENABLED }}" >> "$GITHUB_ENV"
            echo "custom_domain=${{ env.DEFAULT_CUSTOM_DOMAIN }}" >> "$GITHUB_ENV"
            echo "ace_box_name_prefix=${{ env.DEFAULT_ACE_BOX_NAME_PREFIX }}" >> "$GITHUB_ENV"
            echo "dt_tenant=${{ env.DT_TENANT }}" >> "$GITHUB_ENV"
            echo "dt_url_gen3=${{ env.DT_URL_GEN3 }}" >> "$GITHUB_ENV"
          fi

      - name: Convert use_case_validation_tests_enabled to Boolean
        run: |
          if [[ "${{ github.event.inputs.use_case_validation_tests_enabled }}" == "true" ]]; then
            echo "use_case_validation_tests_enabled=true" >> "$GITHUB_ENV"
          else
            echo "use_case_validation_tests_enabled=false" >> "$GITHUB_ENV"
          fi

      - name: Set Outputs
        id: set_outputs
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "use_cases=$(echo '${{ env.use_cases }}' )" >> "$GITHUB_OUTPUT"
            echo "providers=$(echo '${{ github.event.inputs.providers }}' )" >> "$GITHUB_OUTPUT"
            echo "destroy_resources=$(echo '${{ github.event.inputs.destroy_resources }}' )" >> "$GITHUB_OUTPUT"
            echo "use_case_validation_tests_enabled=$(echo '${{ github.event.inputs.use_case_validation_tests_enabled }}' )" >> "$GITHUB_OUTPUT"
            echo "custom_domain=$(echo '${{ github.event.inputs.custom_domain }}' )" >> "$GITHUB_OUTPUT"
            echo "ace_box_name_prefix=$(echo '${{ github.event.inputs.ace_box_name_prefix }}' )" >> "$GITHUB_OUTPUT"
            echo "dt_tenant=$(echo '${{ github.event.inputs.dt_tenant }}' )" >> "$GITHUB_OUTPUT"
            echo "dt_url_gen3=$(echo '${{ github.event.inputs.dt_url_gen3 }}' )" >> "$GITHUB_OUTPUT"
          else
            echo "use_cases=$(echo '${{ env.use_cases }}' )" >> "$GITHUB_OUTPUT"
            echo "providers=${{ env.DEFAULT_PROVIDERS }}" >> "$GITHUB_OUTPUT"
            echo "destroy_resources=${{ env.DESTROY_RESOURCES }}" >> "$GITHUB_OUTPUT"
            echo "use_case_validation_tests_enabled=${{ env.USE_CASE_VALIDATION_TESTS_ENABLED }}" >> "$GITHUB_OUTPUT"
            echo "custom_domain=${{ env.DEFAULT_CUSTOM_DOMAIN }}" >> "$GITHUB_OUTPUT"
            echo "ace_box_name_prefix=${{ env.DEFAULT_ACE_BOX_NAME_PREFIX }}" >> "$GITHUB_OUTPUT"
            echo "dt_tenant=${{ env.DT_TENANT }}" >> "$GITHUB_OUTPUT"
            echo "dt_url_gen3=${{ env.DT_URL_GEN3 }}" >> "$GITHUB_OUTPUT"
          fi
        shell: bash


  deploy_external_usecases:
    needs: set_env_vars
    uses: ./.github/workflows/validation.yaml
    with:
      use_cases: ${{ needs.set_env_vars.outputs.use_cases }}
      providers: ${{ needs.set_env_vars.outputs.providers }}
      destroy_resources: ${{ needs.set_env_vars.outputs.destroy_resources == 'true' }}
      use_case_validation_tests_enabled: ${{ needs.set_env_vars.outputs.use_case_validation_tests_enabled  == 'true' }}
      custom_domain: ${{ needs.set_env_vars.outputs.custom_domain }}
      ace_box_name_prefix: ${{ needs.set_env_vars.outputs.ace_box_name_prefix }}
      dt_tenant: ${{ needs.set_env_vars.outputs.dt_tenant }}
      dt_url_gen3: ${{ needs.set_env_vars.outputs.dt_url_gen3 }}
      dt_oauth_sso_endpoint: ${{ vars.DT_OAUTH_SSO_ENDPOINT }}
      dt_oauth_account_urn: ${{ vars.DT_OAUTH_ACCOUNT_URN }}
    secrets: inherit